# Generated by Django 3.0.6 on 2020-05-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico(a)', 'verbose_name_plural': 'Médico(a)s'},
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.TimeField(verbose_name='horário')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medico', verbose_name='Médico')),
            ],
        ),
    ]
