# Generated by Django 3.0.6 on 2020-05-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200530_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='user',
        ),
    ]
