# Generated by Django 3.0.6 on 2020-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_agenda_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia']},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='horario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario',
            field=models.ManyToManyField(to='core.Horario'),
        ),
    ]
