# Generated by Django 3.0.6 on 2020-05-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ('agenda__dia', 'agenda__horario')},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AddField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Agenda'),
            preserve_default=False,
        ),
    ]
