# Generated by Django 3.0.6 on 2020-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200530_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
